<%@ Page Title="" Language="C#" MasterPageFile="~/secretarypage.master" AutoEventWireup="true" CodeFile="Charges.aspx.cs" Inherits="Charges" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <center>
    <div style="height:110%;width:100%">
           <strong>
           <asp:Label ID="Label21" runat="server" BackColor="#9900CC" CssClass="auto-style7" ForeColor="Wheat" Height="54px" style="background-color: #CCFF66; font-size: large; color: #FF0000;" Text="Maintain Charges" Width="748px"></asp:Label>
           <br />
           <br />
           </strong>
       </div>
            

     <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" DataKeyNames="ID" DataSourceID="SqlDataSource1" ForeColor="Black" Width="501px" EnableModelValidation="True">
                <Columns>
                    <asp:BoundField DataField="Type" HeaderText="Charge Name" SortExpression="Type" />
                    <asp:BoundField DataField="Amount" HeaderText="Amount" SortExpression="Amount" />
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:collegeConnectionString2 %>" DeleteCommand="DELETE FROM charges WHERE (ID = @ID)" SelectCommand="SELECT Type, Amount, ID FROM charges" UpdateCommand="UPDATE charges SET   Amount =@Amount  WHERE (ID = @ID)">
                <DeleteParameters>
                    <asp:Parameter Name="ID" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Amount" />
                    <asp:Parameter Name="ID" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <asp:Label ID="Label5" runat="server" Text="Type:-" Visible="False"></asp:Label>
            <asp:TextBox ID="TextBox12" runat="server" Visible="False"></asp:TextBox>
            <asp:Label ID="Label6" runat="server" Text="Amount:-" Visible="False"></asp:Label>
            <asp:TextBox ID="TextBox16" runat="server" Visible="False"></asp:TextBox>
            <asp:RegularExpressionValidator ID="RegularExpressionValidator4" runat="server" ControlToValidate="TextBox16" Display="Dynamic" ErrorMessage="RegularExpressionValidator" Font-Bold="True" ForeColor="Red" ValidationExpression="[0-9]*" Visible="False">Enter only Digits</asp:RegularExpressionValidator>
            <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Insert New Charge" Visible="False" />
        <br />
    <br />
        </center>
</asp:Content>

