<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Manageuser.aspx.cs" EnableEventValidation="true"  Inherits="Manageuser" MasterPageFile="~/chairman.master" %>

 
     


<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <script type="text/javascript">
	        function print_page() {
	            window.print();
	        }
	    </script>
    <style type="text/css">
	.DataList
{
font-family:Verdana;
	font-size:10pt;
	font-weight:normal;
	color:black;
	}
	       
	</style>
	
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">			    
       <center> <asp:Panel ID="Panel1" runat="server" BackColor="white"  Height="110%" Width="100%">
    <div class="auto-style89">
           <strong>
           <asp:Label ID="Label10" runat="server" BackColor="#9900CC" CssClass="auto-style7" ForeColor="Wheat" Height="54px" style="background-color:#CCFF66; font-size: large; color: #FF0000;" Text="Manage Members" Width="748px"></asp:Label>
           <br />
           <br />
           </strong>
       </div>
      
  
	  <div>
	<a href="#" onclick="javascript :print_page();"><strong><span class="style1">Take printout</span></strong></a>
	</div>
	     <br /><br />
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" EnableModelValidation="True" ForeColor="Black">
        <Columns>
             <asp:BoundField DataField="Role" HeaderText="Role" SortExpression="Role" />
           
            <asp:BoundField DataField="Flat_No" HeaderText="Flat_No" SortExpression="Flat_No" />
             <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
               <asp:ImageField DataImageUrlField="FilePath" ControlStyle-Width="70"  ControlStyle-Height = "70" HeaderText = "Photo"/>
    
            <asp:BoundField DataField="contact_1" HeaderText="contact_1" SortExpression="contact_1" />
            
                <asp:BoundField DataField="contact_2" HeaderText="contact_2" SortExpression="contact_2" />
      
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
             
         
           
            
         
           
          
         
           
            
         
           
</Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        </asp:GridView>

	
	  

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:collegeConnectionString2 %>" SelectCommand="SELECT Flat_No, contact_1, contact_2, email, name, Role, FilePath FROM Login_Info ORDER BY id" UpdateCommand="UPDATE Login_Info SET Role = @Role, Flat_No = @Flat_No, contact_1 = @contact_1, contact_2 = @contact_2, email = @email WHERE (Flat_No = @Flat_No)" DeleteCommand="DELETE FROM Login_Info WHERE (Flat_No = @Flat_No)" >
            <DeleteParameters>
                <asp:Parameter Name="Flat_No" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="Role" />
                <asp:Parameter Name="Flat_No" />
                <asp:Parameter Name="contact_1" />
                <asp:Parameter Name="contact_2" />
                <asp:Parameter Name="email" />
            </UpdateParameters>
        </asp:SqlDataSource>
</asp:Panel>
	</center>
	 
</asp:Content>