<%@ Page Title="" Language="C#" MasterPageFile="~/chairman.master" AutoEventWireup="true" CodeFile="ManageStaff.aspx.cs" Inherits="ManageStaff" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
     <script type="text/javascript">
	        function print_page() {
	            window.print();
	        }
	    </script>
    <style type="text/css">
	.DataList
{
font-family:Verdana;
	font-size:10pt;
	font-weight:normal;
	color:black;
	}
	       
	</style>
	
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
	     <center> <asp:Panel ID="Panel1" runat="server" BackColor="white"  Height="110%" Width="100%">
    <div class="auto-style89">
           <strong>
           <asp:Label ID="Label10" runat="server" BackColor="#9900CC" CssClass="auto-style7" ForeColor="Wheat" Height="54px" style="background-color:#CCFF66; font-size: large; color: #FF0000;" Text="Manage Staff" Width="748px"></asp:Label>
           <br />
           <br />
           </strong>
       </div>
      
  
	
	  <div>
	<a href="#" onclick="javascript :print_page();"><strong><span class="style1">Take printout</span></strong></a>
	</div>
	     <br /><br /><div> <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataSourceID="SqlDataSource1" EnableModelValidation="True" ForeColor="Black" GridLines="Vertical" Width="400px">
                            <AlternatingRowStyle BackColor="#CCCCCC" />
                            <Columns>
                                  
                                <asp:BoundField DataField="Username" HeaderText="Employee Name" SortExpression="Username" />
                                   <asp:ImageField DataImageUrlField="FilePath" ControlStyle-Width="70"  ControlStyle-Height = "70" HeaderText = "Photo"/>
    
                                 <asp:BoundField DataField="Designation" HeaderText="Designation" SortExpression="Designation" />
                                  <asp:BoundField DataField="Date_Joining" HeaderText="Date_Joining" SortExpression="Date_Joining" />
                               
                                 <asp:BoundField DataField="Salary" HeaderText="Salary" SortExpression="Salary" /> 
                                 <asp:BoundField DataField="Date_Resigning" HeaderText="Date_Resigning" SortExpression="Date_Resigning" />
                              
                               
                                <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                                 <asp:BoundField DataField="contact_1" HeaderText="contact_1" SortExpression="contact_1" />
                                <asp:BoundField DataField="contact_2" HeaderText="contact_2" SortExpression="contact_2" />
                                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                               
                                
                           
                                  
                               
                                  
                           
                                  
                               
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        </asp:GridView><br />
                        
               
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:collegeConnectionString2 %>" SelectCommand="SELECT  Designation, Username, Address, contact_1, contact_2, email, Date_Joining, Date_Resigning, Salary, FilePath FROM Staff_Details ORDER BY StaffID" DeleteCommand="DELETE FROM Staff_Details WHERE (Username = @Username)" UpdateCommand="UPDATE Staff_Details SET Designation = @Designation, Username = @Username, Address = @Address, contact_1 = @contact_1, contact_2 = @contact_2, email = @email, Date_Resigning = @Date_Resigning, Salary = @Salary WHERE (Username = @Username)">
                            <DeleteParameters>
                                <asp:Parameter Name="Username" />
                            </DeleteParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="Designation" />
                                <asp:Parameter Name="Username" />
                                <asp:Parameter Name="Address" />
                                <asp:Parameter Name="contact_1" />
                                <asp:Parameter Name="contact_2" />
                                <asp:Parameter Name="email" />
                                <asp:Parameter Name="Date_Resigning" />
                                <asp:Parameter Name="Salary" />
                            </UpdateParameters>
                     </asp:SqlDataSource>
                     </div></asp:Panel>
                     </center>
         
</asp:Content>

